:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

:queues:
    - default
    - [oopsCrawl, 2]

development:
  :concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20